# This file was generated by GoReleaser. DO NOT EDIT.
class Nox < Formula
  desc "A grand unified Elasticsearch infrastructure management cli"
  homepage ""
  version "0.1.2"

  if OS.mac?
    url "https://github.com/procore/nox/releases/download/v0.1.2/nox_0.1.2_64-bit_macOS.tar.gz"
    sha256 "a8dec162490fdc241e6ba418b5e13f5b46194c9126aee1922d81cafa143b153f"
  elsif OS.linux?
    url "https://github.com/procore/nox/releases/download/v0.1.2/nox_0.1.2_64-bit_linux.tar.gz"
    sha256 "e210caf246ce8588c3197f502fc32a665c3377f5c9d145fae4f8ca7e33d9f98a"
  end

  def install
    bin.install "nox"
  end

  test do
    system "#{bin}/nox --help"
  end
end
