# This file was generated by GoReleaser. DO NOT EDIT.
class Nox < Formula
  desc "A grand unified Elasticsearch infrastructure management cli"
  homepage ""
  url "https://github.com/procore/nox/releases/download/v0.1.3/nox_0.1.3_64-bit_macOS.tar.gz"
  version "0.1.3"
  sha256 "6581c32d00085f03263040a7aec75bbfa613e55063eb4ce3d3e6799e770dcff1"

  def install
    bin.install "nox"
  end

  test do
    system "#{bin}/nox --help"
  end
end
