# This file was generated by GoReleaser. DO NOT EDIT.
class Nox < Formula
  desc "A grand unified Elasticsearch infrastructure management cli"
  homepage ""
  version "0.1.1"

  if OS.mac?
    url "https://github.com/procore/nox/releases/download/v0.1.1/nox_0.1.1_64-bit_macOS.tar.gz"
    sha256 "9dc9dfd628ebbaf1a91194c3767723003de5e3d982cb0e8c8ba1a9a1d9c884fa"
  elsif OS.linux?
    url "https://github.com/procore/nox/releases/download/v0.1.1/nox_0.1.1_64-bit_linux.tar.gz"
    sha256 "c58c751e709743f07427f9b901d5edbc506716d7c6f52da4c9f75bd8abe52be6"
  end

  def install
    bin.install "nox"
  end

  test do
    system "#{bin}/nox --help"
  end
end
